#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd compressibleTwoPhaseThermo; wclean; cd ../

cd twoPhaseMixingCentralDyMFoam; wclean; cd ../

wclean

# ----------------------------------------------------------------- end-of-file
