#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd compressibleTwoPhaseThermo; wclean; cd ../

cd twoPhaseMixingCentralDyMFoam; wclean; cd ../

wclean

rm -rf $FOAM_USER_LIBBIN/libcompressibleTwoPhaseThermo.so
rm -rf $FOAM_USER_APPBIN/twoPhaseMixingCentralFoam
rm -rf $FOAM_USER_APPBIN/twoPhaseMixingCentralDyMFoam

# ----------------------------------------------------------------- end-of-file
