#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd compressibleTwoPhaseThermo; wmake libso; cd ../

cd twoPhaseMixingCentralDyMFoam; wmake; cd ../

wmake

# ----------------------------------------------------------------- end-of-file
